GarfieldWAY/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pins.urls')),
    url(r'^pins/', include('pins.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]

pins/urls.py
from django.conf.urls import url
from . import views

app_name='pins'

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url('create/', views.create, name='create'),
   url('test/', views.test, name= 'test'),
   url(r'^edit/(?P<pin_id>[0-9]+)/$', views.edit, name= 'edit'),
   url(r'^delete/(?P<pin_id>[0-9]+)/$', views.delete, name='delete'),
   url('getallrooms/', views.getAllRoomPins, name = 'number of pins '),
   url('vote/', views.vote, name='vote'),
   url('mypinsfilter/', views.mypinsfilter, name='mypinsfilter'),
   url('typefilter/', views.typefilter, name='typefilter'),
   url('lowestroomfilter/', views.lowestroomfilter, name='lowestroomfilter'),
   url('highestroomfilter/', views.highestroomfilter, name='highestroomfilter'),
   url('recentlypublishedfilter/', views.recentlypublishedfilter, name='recentlypublishedfilter'),
   url('oldestpublishedfilter/', views.oldestpublishedfilter, name='oldestpublishedfilter'),
]   

pins/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from django import forms


def validate_room (pin_room):
   print ("THE PIN ROOM IS: " + pin_room)
   if not (int(pin_room)>100 and int(pin_room)<140 or (int(pin_room)>=200 and int(pin_room)<240) or (int(pin_room)>=300 and int(pin_room)<340)):
      raise ValidationError(
         _('%(pin_room)s is not a valid room number'),
            params={'pin_room': pin_room},
        )

TYPE_CHOICES = (
    ('Club', 'Club'),
    ('Public', 'Public'),
    ('Private', 'Private'),
    ('Other', 'Other'),
)
# Create your models here.


class Pin(models.Model):
   pin_name = models.CharField(max_length=100)
   pin_description = models.CharField(max_length=300, null = True, blank=True)
   pin_room = models.CharField(max_length=4, null=True, blank=True)
   other_pin_room = models.CharField(max_length=100, null=True, blank=True)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)
   
   def save(self, **kwargs):
      self.clean()
      return super(Pin, self).save(**kwargs)


   pub_date = models.DateTimeField(auto_now_add = True)
   pin_type = models.CharField(choices = TYPE_CHOICES, max_length=10, default='Other', null=True) #pull down for the types of activities
   voters=models.ManyToManyField(User, related_name = 'voters')
   votes=models.IntegerField(default=0)
   date = models.DateTimeField(auto_now_add = False, blank=True)
   user = models.ForeignKey(User, related_name = 'user', on_delete=models.CASCADE)
   
   def __str__(self):
      return self.pin_name      
   
   

pins/forms.py
from django import forms

from django.forms import Textarea, DateTimeField, DateField
from .models import Pin
from .widgets import DateTimeLocalWidget, DateTimeLocalField
from django.db import models
from django.contrib.admin import widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import SelectDateWidget

from django.forms import Textarea
from .models import Pin
from django.db import models
from django.contrib.admin import widgets
import datetime
import json


class PinForm(forms.ModelForm):
    date = DateTimeLocalField()
    
    class Meta:
        model = Pin
        exclude = ('pub_date', 'user', 'votes','voters')
        labels = {
            'pin_name': 'Name ',
            'pin_room': 'Room ',
            'other_pin_room': 'Other Room ',
            'pin_description': 'Description',
            'pin_type': 'Type',
            'votes':'Up Votes'
            
        }
        help_texts = {
            'pin_room': '100-124 or 200-240 or 300-340 (Optional)',
            'other_pin_room': 'e.g. Gym, Commons, Field (Optional)',
        }
        widgets = {
            'pin_description': Textarea(),
        }

#     def clean(self):
#         # print(self.cleaned_data)
#         # cleaned_data = super(PinForm, self).clean()
#         # print("clenaed data: " +  json.dumps(cleaned_data))
#         # print("pin room: " + self.cleaned_data["pin_room"])
#         pin_room = int(self.cleaned_data["pin_room"])
#         print("pin room: " + str(pin_room))
#         if not((pin_room>=100 and pin_room<124) or (pin_room>=200 and pin_room<240) or (pin_room>=300 and pin_room<340)): 
#             print("not valid room")
#             raise forms.ValidationError(
#                 ('%(pin_room)s is not a valid room number'),
#                 params={'pin_room': pin_room},
#             )
#         return self.cleaned_data


    # def validate_room():
    #     print ("THE PIN ROOM IS: " + self.pin_room)
        # if not (int(self.pin_room)>100 and int(self.pin_room)<140):
        #     raise ValidationError(
        #         _('%(pin_room)s is not an valid room number'),
        #         params={'pin_room': pin_room},
        #     )



class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )

pins/views.py
from __future__ import unicode_literals
from django.contrib.auth import login, authenticate
from django.shortcuts import render, get_object_or_404

from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, redirect
from .models import Pin
from .forms import PinForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from django.forms.widgets import SelectDateWidget
from django.core.management.base import BaseCommand, CommandError
from datetime import datetime, timedelta


def index(request):
   buffertime = (timezone.now() - timedelta(days=1))
   passedtime = (timezone.now() - timedelta(days=7))
   upcoming_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('date')
   passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
   context = {
        'pin_list': upcoming_pin_list,
        'old_pin_list': passed_pin_list,
   }
   template = loader.get_template('pins/index.html')
   return HttpResponse(template.render(context, request))   

def vote(request):
   pin = Pin.objects.get(id=request.GET.get('pin_id'))
   user=request.user
   if request.GET.get('vote') =='upvote' :
      if not pin.voters.filter(id=user.id).exists():
         pin.voters.add(request.user)
   else:
      if pin.voters.filter(id=user.id).exists():
         pin.voters.remove(request.user)
         
   pin.votes=pin.voters.count()
   pin.save()
   return redirect('/pins')

def mypinsfilter(request):
   buffertime = (timezone.now() - timedelta(days=1))
   passedtime = (timezone.now() - timedelta(days=7))
   passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
   current_user = request.user
   if current_user.is_authenticated:
      my_pin_list = Pin.objects.filter(user=request.user, date__gte=buffertime).order_by('-pub_date')
      context = {
        'pin_list': my_pin_list,
        'old_pin_list': passed_pin_list,
      }
      template = loader.get_template('pins/index.html')
      return HttpResponse(template.render(context, request))
   else:
      return redirect('/accounts/login') 

def recentlypublishedfilter(request):
    buffertime = (timezone.now() - timedelta(days=1))
    passedtime = (timezone.now() - timedelta(days=7))
    passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
    latest_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('-pub_date')
    context = {
        'pin_list': latest_pin_list,
        'old_pin_list': passed_pin_list,
    }
    template = loader.get_template('pins/index.html')
    return HttpResponse(template.render(context, request))
    
def oldestpublishedfilter(request):
    buffertime = (timezone.now() - timedelta(days=1))
    passedtime = (timezone.now() - timedelta(days=7))
    passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
    latest_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('pub_date')
    context = {
        'pin_list': latest_pin_list,
        'old_pin_list': passed_pin_list,
    }
    template = loader.get_template('pins/index.html')
    return HttpResponse(template.render(context, request))

def lowestroomfilter(request):
   buffertime = (timezone.now() - timedelta(days=1))
   passedtime = (timezone.now() - timedelta(days=7))
   passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
   room_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('pin_room', 'date')
   context = {
        'pin_list': room_pin_list,
        'old_pin_list': passed_pin_list,
   }
   template = loader.get_template('pins/index.html')
   return HttpResponse(template.render(context, request))
   
def highestroomfilter(request):
   buffertime = (timezone.now() - timedelta(days=1))
   passedtime = (timezone.now() - timedelta(days=7))
   passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
   room_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('-pin_room', 'date')
   context = {
        'pin_list': room_pin_list,
        'old_pin_list': passed_pin_list,
   }
   template = loader.get_template('pins/index.html')
   return HttpResponse(template.render(context, request))

def typefilter(request):
   buffertime = (timezone.now() - timedelta(days=1))
   passedtime = (timezone.now() - timedelta(days=7))
   passed_pin_list = Pin.objects.filter(date__lt=buffertime, date__gte=passedtime).order_by('-date')
   type_pin_list = Pin.objects.filter(date__gte=buffertime).order_by('pin_type', 'date')
   context = {
        'pin_list': type_pin_list,
        'old_pin_list': passed_pin_list,
   }
   template = loader.get_template('pins/index.html')
   return HttpResponse(template.render(context, request))

def create(request):
   current_user = request.user
   if current_user.is_authenticated:
       if request.method == 'GET':
          latest_pin_list = Pin.objects.order_by('-date')
          template = loader.get_template('pins/create.html')
          context = {
              'pin_list': latest_pin_list, 'pin_form': PinForm,
          }
          return HttpResponse(template.render(context, request))
          
       elif request.method == 'POST':
          pin = Pin ()  
          pin.user = current_user
          pin.pin_name = request.POST.get('pin_name')
          pin.pin_room = request.POST.get('pin_room')
          pin.other_pin_room = request.POST.get('other_pin_room')
          pin.pin_description = request.POST.get('pin_description')
          pin.date = request.POST.get('date')
          pin.pin_type = request.POST.get('pin_type')
          pin.save()
          form = PinForm(request.POST, instance=pin)
          if request.POST.get('_save') is not None:
            return redirect('/pins')
          else:
            return redirect('/pins/create')
   else:
      return redirect('/accounts/login')

def edit(request, pin_id):
    pin = get_object_or_404(Pin, pk=pin_id)
    if request.user != pin.user:
      return redirect('/pins')
    if request.method == 'POST':
      form = PinForm(request.POST, instance=pin)
      if form.is_valid():
         pin = form.save(commit=False)
         pin.save()
      if request.POST.get('_save') is not None: 
         pin.pin_name = request.POST.get('pin_name')
         pin.pin_room = request.POST.get('pin_room')
         pin.other_pin_room = request.POST.get('other_pin_room')
         pin.pin_description = request.POST.get('pin_description')
         pin.date = request.POST.get('date')
         pin.pin_type = request.POST.get('pin_type')
         pin.save()
         return redirect('/pins')
    else:
      form = PinForm(instance=pin)
    template = loader.get_template('pins/edit.html')
    context = {
      'pin_form': form,
    }
    return HttpResponse(template.render(context, request))

def delete(request, pin_id):
   pin = get_object_or_404(Pin, pk=pin_id)
   if request.user != pin.user:
      return redirect('/pins')
   if request.method == 'POST':
      form = PinForm(request.POST, instance=pin)
      pin.delete()
      return redirect('/pins')
   else:
      form = PinForm(instance=pin)
   template = loader.get_template('pins/delete.html')
   context = {
      'pin_form': form,
   }
   return HttpResponse(template.render(context, request))


def purge_old_pins (request):
   #  schedule.every().day.at("10:18").do(purge_old_pins(request))
   #  while True:
   #     schedule.run_pending()
   #     #time.sleep(1) 
       now = timezone.now()
       upcoming = Pin.objects.filter(date__gte=now).order_by('date')
       passed = Pin.objects.filter(date__lt=now).order_by('-date')
       if (passed):
          passed.exclude() #hides pins that have passed just while on the purge old pins url
          #passed.delete()
       upcoming_pin_list = list(upcoming)
       context = {
          'pin_list': upcoming_pin_list
       }
       template = loader.get_template('pins/index.html')
       return HttpResponse(template.render(context, request))

# def clear(request):
#     Pin.objects.all().delete()
#     return HttpResponse ('Cleared pins')

def test(request):
    test_pin = Pin ()
    test_pin.pin_name = 'test pin!'
    test_pin.pin_room = 105
    test_pin.pin_description = 'this is a test pin'
    test_pin.date = '2018-12-10 09:23:00'
    test_pin.save()
    return HttpResponse('Test pin')
    
def getAllRoomPins (request):
    return HttpResponse("Number of Pins: " + str(numberOfPins))

pins/templates/pins/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Add pin</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/forms.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/widgets.css' %}" type="text/css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
	
	<!-- <script type="text/javascript" src="/my_admin/jsi18n/"></script> -->
	<!-- <script type="text/javascript" src="/media/admin/js/core.js"></script> -->
	<!-- <link rel="stylesheet" type="text/css" href="/media/admin/css/global.css"/> -->

</head>
<body>
    <div id="main">

        <div id="header">
            <h1 id="site">
                <a href="/pins">GarfieldWAY</a>
            </h1>
                <div id="user-tools">

                {% if user.is_authenticated %}
				
                Welcome,
                <strong>{{ user.get_username }}</strong>.
				
				{% else %}
				
				Welcome,
                <strong>guest</strong>.
				
				{% endif %}

				<a href="/pins" id="userlink">Home</a> /
				
				<a href="/accounts/profile" id="userlink">Profile</a> /
				
				<a href="/accounts/signup" id="userlink">Sign up</a> /

				<a href="/accounts/login" id="userlink">Log in</a> /

				<a href="/accounts/logout" id="userlink">Log out</a>

                </div>
        </div>
		
		<div class="breadcrumbs">
		
            <a href="/pins/">Home ›</a> <a href="/pins/">Pins ›</a> <a href="/pins/create">Add pin</a>
        
		</div>
		
		<div id="content" class="colM">

            <h1>Add pin</h1>
		
			<div id="content-main">
			
				<ul class="object-tools">
				
					<li>
					
						<a href="/pins/" class="addlink">Cancel</a>
					
					</li>
					
                </ul>
			
			
				<form action="" method="post" id="pin_form" novalidate="">
					{% csrf_token %}
						{% for field in pin_form %}
						
						  <p>
						  
							<!-- Field labels and input boxes-->
							{{ field.label_tag }}<br>
							{{ field }}
							
							<!-- Help texts-->
							<div class="helptexts">
							{% if field.help_text %}
							  <small>{{ field.help_text | safe}}</small>
							{% endif %}
							</div>
							
							<!-- Error messages -->
							<div class="errormessages"
							{% for error in field.errors %}
							  <p style="color: red">{{ error | safe }}</p>
							{% endfor %}
							</div>
							
						  </p>
						  
						{% endfor %}
					
					<div class="submit-row">
						<input type="submit" value="Save and add another" name="_addanother">
						<input type="submit" value="Save and continue editing" name="_continue">
						<input type="submit" value="Save" class="default" name="_save">
					</div>
				</form>
				
			</div>
			
		</div>
		
    </div>
	
</body>
</html>

pins/templates/pins/datepicker.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Static Example</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker();
      });
    </script>

  </body>
</html>

pins/templates/pins/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Pin List</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/forms.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css">
	<link rel="stylesheet" href="{% static 'css/widgets.css' %}" type="text/css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
</head>
<body>

	<div id="main">

        <div id="header">
            <h1 id="site">
                <a href="/pins">GarfieldWAY</a>
            </h1>
                <div id="user-tools">
				
				{% if user.is_authenticated %}
				
                Welcome,
                <strong>{{ user.get_username }}</strong>.
				
				{% else %}
				
				Welcome,
                <strong>guest</strong>.
				
				{% endif %}
				
				<a href="/pins" id="userlink">Home</a> /
				
				<a href="/accounts/profile" id="userlink">Profile</a> /
				
				<a href="/accounts/signup" id="userlink">Sign up</a> /

				<a href="/accounts/login" id="userlink">Log in</a> /

				<a href="/accounts/logout" id="userlink">Log out</a> 				

                </div>
        </div>
		
		<div class="breadcrumbs">
		
            <a href="/pins/">Home ›</a> <a href="/pins/">Pins</a>
			
        </div>
		
		<div id="content" class="flex">
		
            <h1>Pin List</h1>
		
			<div id="content-main">
				
					<div class="dropdown">
						<button onclick="openDropdown()" class="dropbtn">Filter pin list</button>
							<div id="myDropdown" class="dropdown-content">	
								<a href="/pins">Upcoming</a>
								<a href="/pins/mypinsfilter/">My Pins</a>
								<a href="/pins/typefilter/">Type</a>
								<a href="/pins/lowestroomfilter/">Lowest Room Number</a>
								<a href="/pins/highestroomfilter/">Highest Room Number</a>
								<a href="/pins/recentlypublishedfilter">Recently Published</a>
								<a href="/pins/oldestpublishedfilter">Oldest Published</a>	
							</div>
					</div>					

				<ul class="object-tools">
					<li>
						<a href="/pins/create/" class="addlink">Add pin</a>
					</li>
                </ul>

				{% for pin in pin_list %}
					
					<div class="pinlist">
						
						<div>
						
							<h1>
								
								{{ pin.pin_name }}			
						
							</h1>
							
						</div>	
						
						<li>
							<b>Description:</b> {{ pin.pin_description }}
						</li>
						
						<li>
							<b>Room:</b> {{ pin.pin_room }}
						</li>
						
						<li>
							<b>Other Room:</b> {{ pin.other_pin_room }}
						</li>
						
						<li>
							<b>Type:</b> {{ pin.pin_type }}
						</li>
						
						<li>
							<b>Date:</b> {{ pin.date }}
						</li>
				
						<li>
							<b>Up Votes:</b> {{pin.votes}}
						</li>
						
						<li>
							<b>Posted by:</b> @{{pin.user.get_username}}
						</li>
						
						<div id="linkdiv">
						
						{% if user == pin.user %}
				
							<a href="{% url 'pins:delete' pin.id %}" id="deletelink">Delete pin</a>
						
							<a href="{% url 'pins:edit' pin.id %}" id="changelink">Edit pin</a>
							
						{% endif %}
						
						</div>
							
						{% if user.is_authenticated %}
						<form method="get" action="/pins/vote/" />
							<input type="hidden" name="pin_id" value="{{ pin.id }}" voter=user />
			
							<button type="upvote" id="upvote" name="vote" value="upvote" >I'm coming!</button>
							
							<button type="downvote" id="downvote" name="vote" value="downvote" >Can't make it!</button>
							
						</form>
						{% endif %}
						
						
						
				
					</div>
					
				{% endfor %}	
				
				<br />
				
				<!-- Dropdown for old pins starts here -->
				<a>
				<button onclick="openDropdown2()" id="accountbutton">Show Passed Pins</button>
					<div id="myDropdown2" class="dropdown-profile-content">
					
						{% for pin in old_pin_list %}
							
							<div class="pinlist">
								
								<div>
								
									<h1>
										
										{{ pin.pin_name }}			
								
									</h1>
									
								</div>	
								
								<li>
									<b>Description:</b> {{ pin.pin_description }}
								</li>
								
								<li>
									<b>Room:</b> {{ pin.pin_room }}
								</li>
								
								<li>
									<b>Other Room:</b> {{ pin.other_pin_room }}
								</li>
								
								<li>
									<b>Type:</b> {{ pin.pin_type }}
								</li>
								
								<li>
									<b>Date:</b> {{ pin.date }}
								</li>
						
								<li>
									<b>Up Votes:</b> {{pin.votes}}
								</li>
								
								<li>
									<b>Posted by:</b> @{{pin.user.get_username}}
								</li>
								
								<div id="linkdiv">
								
								{% if user == pin.user %}
						
									<a href="{% url 'pins:delete' pin.id %}" id="deletelink">Delete pin</a>
								
									<a href="{% url 'pins:edit' pin.id %}" id="changelink">Edit pin</a>
									
								{% endif %}
								
								</div>
										
								<form method="get" action="/pins/vote/" />
									<input type="hidden" name="pin_id" value="{{ pin.id }}" />
									<button type="upvote" id="upvote" name="vote" value="1">I'm coming!</button>
									<button type="downvote" id="downvote" name="vote" value="-1">Can't make it!</button>
								</form>
						
							</div>
							
						{% endfor %}	

					</div>	
				</a>
				
		</div>
	
	</div>
	
	<footer class="footer"> 
		<a id="footerlink">Copyright © 2019 Trevor Ing, Micah Tratt, Aaron Tou, Jack Bryant. All rights reserved. | </a><a href="/static/termsofservice.txt" id="footerlink">Terms of Service</a>
	</footer>
	
</body>

				
						
<script>
	/* When the user clicks on the button, 
	toggle between hiding and showing the dropdown content */
	function openDropdown() {
		document.getElementById("myDropdown").classList.toggle("show");
		}
	// Close the dropdown if the user clicks outside of it
		window.onclick = function(event) {
			if (!event.target.matches('.dropbtn')) {
				var dropdowns = document.getElementsByClassName("dropdown-content");
				var i;
				for (i = 0; i < dropdowns.length; i++) {
					var openDropdown = dropdowns[i];
					if (openDropdown.classList.contains('show')) {
						openDropdown.classList.remove('show');
					}
				}
			}
		}
	function openDropdown2() {
		document.getElementById("myDropdown2").classList.toggle("show");
		}
</script>

<script>
	if ( window.history.replaceState ) {
	window.history.replaceState( null, null, window.location.href );
}
</script>


</html>